### ISSUE TITLE
Is Access to the Labeled-3D Dataset for Human Preference Evaluation Possible?

### ISSUE THREAD

**Issue by seooyxx** [liuff19/DreamReward#3]
Thank you for sharing your fascinating research! 

I am very interested in the academic use of this dataset. 
Are there any plans to release the Labeled-3D dataset mentioned in your paper? 
If it has already been made available, could you please inform me where I can access it? 

Thank you!

**Comment by JAMESYJL** [comment]
Thank you for your interest! 

The Labeled-3D dataset will be publicly available in a few weeks.

**Comment by AndroExpert** [comment]
Are the few weeks over, does this work or just hot air ?
